services:
  express-server:
    build: ./express-server
    volumes:
      - ./express-server:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/NoWasteDB
    command: pnpm start:docker
    
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: NoWasteDB
      POSTGRES_HOST_AUTH_METHOD: trust
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres